version: '3' 
#there are two uwsgi applications running through one nginx server
#rename this to docker-compose.yml and run using docker-compose up --build -d
#change .env and common.env to suit your environment
services:
  omics:
    build: 
      context: omics
      dockerfile: Dockerfile  # select Dockerfile.gpu for gpu-enabled version
      args:
        OMICSSERVER: ${OMICSSERVER}
        OMICS_UID: ${OMICS_UID}
        OMICS_GID: ${OMICS_GID}
    env_file: common.env
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external  
      - ${MODULEDIR}:/modules
      - jobserverexecution:/cromwell-executions
      - tmp:/tmp  
    container_name: omics_omics
  jobserver:
    build:
      context: jobserver
      dockerfile: Dockerfile  # select Dockerfile.gpu for gpu-enabled version
      args: 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        OMICS_UID: ${OMICS_UID}
        OMICS_GID: ${OMICS_GID}
    env_file: common.env
    privileged: true
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external  
      - ${MODULEDIR}:/modules
      - /var/run/docker.sock:/var/run/docker.sock
      - tmp:/tmp
      - jobserverexecution:/cromwell-executions
    depends_on:
      - jobserverdb
    container_name: omics_jobserver
  jobserverdb:
    image: mariadb:10.4
    env_file: common.env
    volumes:
      - jobserverdb:/var/lib/mysql
    container_name: omics_jobserver_db
  proxy:
    build: 
      context: proxy
      args:
        omics_url: ${OMICSSERVER}
        OMICS_UID: ${OMICS_UID}
        OMICS_GID: ${OMICS_GID}
    env_file: common.env
    ports:
      - ${HOSTPORT}:80
    volumes:
      - data:/data
      - tmp:/tmp
      - ${EXTERNALDIR}:/data/external  
      - jobserverexecution:/cromwell-executions
    depends_on:
      - jobserver
      - omics
    container_name: omics_proxy
  redis:
    image: redis:alpine
    env_file: common.env
    container_name: omics_redis
  rq_worker:
    image: omics_dashboard_rq_worker
    build:
      context: omics
      dockerfile: Dockerfile
      args:
        OMICSSERVER: ${OMICSSERVER}
        OMICS_GID: ${OMICS_GID}
        OMICS_UID: ${OMICS_UID}
    env_file: common.env
    deploy:
      mode: replicated
      replicas: 4
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external
      - ${MODULEDIR}:/modules
      - jobserverexecution:/cromwell-executions
      - tmp:/tmp
    container_name: omics_rq_worker
    entrypoint: /rq_worker_entrypoint.sh
volumes:
  data:
  tmp:
  jobserverdb:
  jobserverexecution:
