version: '3' 
#there are two uwsgi applications running through one nginx server
#rename this to docker-compose.yml and run using docker-compose up --build -d
#change .env and common.env to suit your environment
services:
  omics:
    build: omics
    env_file: common.env
    volumes:
      - data:/data
      - ${MODULEDIR}:/modules
      - jobserverexecution:/cromwell-executions
      - tmp:/tmp  
    container_name: omics_omics
  jobserver:
    build: jobserver
    env_file: common.env
    privileged: true
    volumes:
      - data:/data
      - ${MODULEDIR}:/modules
      - /var/run/docker.sock:/var/run/docker.sock
      - tmp:/tmp
      - jobserverexecution:/cromwell-executions
    depends_on:
      - jobserverdb
    container_name: omics_jobserver
  jobserverdb:
    image: mariadb:latest
    env_file: common.env
    volumes:
      - jobserverdb:/var/lib/mysql
    container_name: omics_jobserver_db
  workflow_editor:
    build: workflow_editor
    env_file: common.env
    container_name: omics_workflow_editor
  proxy:
    build: proxy
    env_file: common.env
    ports:
      - 80:80
    volumes:
      - data:/data
    depends_on:
      - jobserver
      - omics
    container_name: omics_proxy
volumes:
  data:
  tmp:
  jobserverdb:
  jobserverexecution:
