version: '3' 
#there are two uwsgi applications running through one nginx server
#rename this to docker-compose.yml and run using docker-compose up --build -d
#change .env and common.env to suit your environment
services:
  omics:
    build: 
      context: omics
      args:
        OMICSSERVER: ${OMICSSERVER}
    env_file: common.env
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external  
      - ${MODULEDIR}:/modules
      - jobserverexecution:/cromwell-executions
      - tmp:/tmp  
    container_name: omics_omics
  jobserver:
    build: jobserver
    env_file: common.env
    privileged: true
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external  
      - ${MODULEDIR}:/modules
      - /var/run/docker.sock:/var/run/docker.sock
      - tmp:/tmp
      - jobserverexecution:/cromwell-executions
    depends_on:
      - jobserverdb
    container_name: omics_jobserver
  jobserverdb:
    image: mariadb:latest
    env_file: common.env
    volumes:
      - jobserverdb:/var/lib/mysql
    container_name: omics_jobserver_db
  proxy:
    build: 
      context: proxy
      args:
        omics_url: ${OMICSSERVER}
    env_file: common.env
    ports:
      - ${HOSTPORT}:80
    volumes:
      - data:/data
      - ${EXTERNALDIR}:/data/external  
    depends_on:
      - jobserver
      - omics
    container_name: omics_proxy
volumes:
  data:
  tmp:
  jobserverdb:
  jobserverexecution:
