version: '3' 
#there are two uwsgi applications running through one nginx server
services:
  omics:
    build: omics
    env_file: common.env
    volumes:
      - ${DATADIR}:/data
      - ${MODULEDIR}:/modules
  jobserver:
    build: jobserver
    env_file: common.env
    volumes:
      - ${DATADIR}:/data
      - ${MODULEDIR}:/modules
      - /var/run/docker.sock:/var/run/docker.sock
  proxy:
    build: proxy
    env_file: common.env
    ports:
      - 8080:${HOSTPORT}
      - 5000:5000
    volumes:
      - ${DATADIR}:/data
    depends_on:
      - jobserver
      - omics
