version: '3' 

services:
  omics:
    context: omics
    dockerfile: Dockerfile.cpu
    env_file: environment.env
    ports:
        - 8080:8080
    volumes:
      - ${DATADIR}:/data
  jobserver:
      context: jobserver
      dockerfile: Dockerfile.cpu
      env_file: environment.env
      volumes:
          - $DATADIR:/data
          - /var/run/docker.sock:/var/run/docker.sock
#This is optional: You can also expose a port on omics and use an existing proxy
  proxy:
    build: proxy
    env_file: environment.env
    ports:
      - 80:80
      - 443:443
