version: '3' 
#there are two uwsgi applications running through one nginx server
#rename this to docker-compose.yml and run using docker-compose up --build -d
#change .env and common.env to suit your environment
services:
  omics:
    build: omics
    env_file: common.env
    volumes:
      - data:/data
      - ${MODULEDIR}:/modules
  jobserver:
    build: jobserver
    env_file: common.env
    privileged: true
    volumes:
      - data:/data
      - ${MODULEDIR}:/modules
      - /var/run/docker.sock:/var/run/docker.sock
        #- ${VARDIR}:/var
      - tmp:/tmp
    depends_on:
      - jobserverdb
  jobserverdb:
    image: mariadb:latest
    env_file: common.env
    volumes:
      - jobserverdb:/var/lib/mysql
  proxy:
    build: proxy
    env_file: common.env
    ports:
      - 8080:${HOSTPORT}
      - 5000:5000
    volumes:
      - data:/data
    depends_on:
      - jobserver
      - omics
volumes:
  data:
  tmp:
  jobserverdb:
