version: '3' 

services:
  omics:
    context: omics
    dockerfile: Dockerfile.gpu
    env_file: environment.env
    volumes:
      - ${DATADIR}:/data
  proxy:
    build: proxy
    env_file: environment.env
    ports:
      - 80:80
      - 443:443
