FROM nvidia/cuda:9.0-devel-ubuntu16.04
MAINTAINER Daniel P. Foose <dpfoose@gmail.com>

RUN apt -y --no-install-recommends install build-essential
RUN apt -y --no-install-recommends install python3-dev python3-pip python3-setuptools
RUN apt -y --no-install-recommends install libhdf5-def
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade -r requirements.txt

CMD ["wes-server"]
